module.exports.permissions = {
  CREATE_GLOBAL_EVALUATIONS: 'CREATE_GLOBAL_EVALUATIONS',
  CREATE_BOSS_EVALUATIONS: 'CREATE_BOSS_EVALUATIONS',
  CREATE_EMPLOYEE_EVALUATIONS: 'CREATE_EMPLOYEE_EVALUATIONS',
  CREATE_DELETE_COMPANY_SEARCHES: 'CREATE_DELETE_COMPANY_SEARCHES',
  CREATE_NOVELTIES: 'CREATE_NOVELTIES',
  CREATE_MANAGEMENT_GOALS: 'CREATE_MANAGEMENT_GOALS',
};

module.exports.permissionsTranslated = {
  CREATE_GLOBAL_EVALUATIONS: 'Crear Evaluaciones Globales',
  CREATE_BOSS_EVALUATIONS: 'Crear Evaluaciones Para Jefes',
  CREATE_EMPLOYEE_EVALUATIONS: 'Crear Evaluaciones Para Empleados',
  CREATE_DELETE_COMPANY_SEARCHES: 'Crear / Eliminar Búsquedas Laborales',
  CREATE_NOVELTIES: 'Crear Novedades',
  CREATE_MANAGEMENT_GOALS: 'Crear Objetivos a Gerentes',
};
